src/Workers/AuctionSystem.Worker.Runner/JobManager.cs
src/Workers/AuctionSystem.Worker.Runner/Models/ItemDto.cs

Send message to the owner of auction to notify that the item is sold

---

src/Web/AuctionSystem.Web/Views/Shared/_LoginPartial.cshtml

Add neccessary class to align properly account dropdown menu

---

src/Web/AuctionSystem.Web/Infrastructure/Extensions/ApplicationBuilderExtensions.cs
src/Web/AuctionSystem.Web/Infrastructure/Middleware/MiddlewareConstants.cs
src/Web/AuctionSystem.Web/Infrastructure/Middleware/SecurityHeadersBuilder.cs
src/Web/AuctionSystem.Web/Infrastructure/Middleware/SecurityHeadersMiddleware.cs
src/Web/AuctionSystem.Web/Infrastructure/Middleware/SecurityHeadersPolicy.cs
src/Web/AuctionSystem.Web/Startup.cs

Add default security headers

---

src/Web/AuctionSystem.Web/Views/Shared/_LoginPartial.cshtml

Fix inappropriate menus

---

src/AuctionSystem.Common/AuctionSystem.Common.csproj
src/Data/AuctionSystem.Data/AuctionSystem.Data.csproj
src/Data/AuctionSystem.Models/AuctionSystem.Models.csproj
src/Data/AuctionSystem.Models/Bid.cs
src/Data/AuctionSystem.Models/Category.cs
src/Data/AuctionSystem.Models/Item.cs
src/Data/AuctionSystem.Models/Picture.cs
src/Data/AuctionSystem.Models/SubCategory.cs
src/Services/AuctionSystem.Services.Models/AuctionSystem.Services.Models.csproj
src/Services/AuctionSystem.Services.Models/Item/ItemCreateServiceModel.cs
src/Services/AuctionSystem.Services/AuctionSystem.Services.csproj
src/Services/AuctionSystem.Services/Implementations/ItemsService.cs
src/Services/AuctionSystem.Services/Implementations/PictureService.cs
src/Services/AuctionSystem.Services/Interfaces/IPictureService.cs
src/Tests/AuctionSystem.Services.Tests/AuctionSystem.Services.Tests.csproj
src/Tests/AuctionSystem.Services.Tests/Tests/ItemsServiceTests.cs
src/Web/AuctionSystem.Web/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
src/Web/AuctionSystem.Web/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
src/Web/AuctionSystem.Web/AuctionSystem.Web.csproj
src/Web/AuctionSystem.Web/Controllers/ItemsController.cs
src/Web/AuctionSystem.Web/Controllers/PicturesController.cs
src/Web/AuctionSystem.Web/Startup.cs
src/Workers/AuctionSystem.Worker.Runner/AuctionSystem.Worker.Runner.csproj

Upgrade to ASP.NET Core 3.1

---

src/AuctionSystem.Common/AuctionSystem.Common.csproj
src/AuctionSystem.Common/AutoMapping/Profiles/DefaultProfile.cs
src/Services/AuctionSystem.Services/AuctionSystem.Services.csproj
src/Services/AuctionSystem.Services/Implementations/BaseService.cs
src/Services/AuctionSystem.Services/Implementations/BidService.cs
src/Services/AuctionSystem.Services/Implementations/CategoriesService.cs
src/Services/AuctionSystem.Services/Implementations/ItemsService.cs
src/Services/AuctionSystem.Services/Implementations/PictureService.cs
src/Services/AuctionSystem.Services/Implementations/UserService.cs
src/Tests/AuctionSystem.Services.Tests/AuctionSystem.Services.Tests.csproj
src/Tests/AuctionSystem.Services.Tests/Setup/TestSetup.cs
src/Tests/AuctionSystem.Services.Tests/Tests/BaseTest.cs
src/Tests/AuctionSystem.Services.Tests/Tests/BidServiceTests.cs
src/Tests/AuctionSystem.Services.Tests/Tests/CategoriesServiceTests.cs
src/Tests/AuctionSystem.Services.Tests/Tests/ItemsServiceTests.cs
src/Tests/AuctionSystem.Services.Tests/Tests/UserServiceTests.cs
src/Web/AuctionSystem.Web/Areas/Admin/Controllers/UsersController.cs
src/Web/AuctionSystem.Web/Areas/Bid/Controllers/BidController.cs
src/Web/AuctionSystem.Web/AuctionSystem.Web.csproj
src/Web/AuctionSystem.Web/Controllers/HomeController.cs
src/Web/AuctionSystem.Web/Controllers/ItemsController.cs
src/Web/AuctionSystem.Web/Infrastructure/Collections/Cache.cs
src/Web/AuctionSystem.Web/Startup.cs

Update AutoMapper to version 9

---

src/Web/AuctionSystem.Web/Startup.cs

Fix bug where error pages were not displayed in case of wrong url

---

src/Web/AuctionSystem.Web/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
src/Web/AuctionSystem.Web/Areas/Identity/Pages/Account/ResetPassword.cshtml
src/Web/AuctionSystem.Web/Areas/Identity/Pages/Account/ResetPassword.cshtml.cs

Refactor forgotten password page

---

src/Services/AuctionSystem.Services/Implementations/ItemsService.cs
src/Services/AuctionSystem.Services/Implementations/PictureService.cs
src/Services/AuctionSystem.Services/Interfaces/IPictureService.cs

Fix picture deletion when deleting item

---

src/Web/AuctionSystem.Web/ViewModels/Item/LiveItemViewModel.cs

Fix missing mapping between LiveItemViewModel and LiveItemServiceModel

---

src/Web/AuctionSystem.Web/Areas/Bid/Views/Bid/Details.cshtml
src/Web/AuctionSystem.Web/SignalRHubs/BidHub.cs
src/Web/AuctionSystem.Web/wwwroot/source/bidding/js/bid.js

Closes #198 
Closes #200 
Fixes #175

Improve client-side bidding code

---

src/Presentation/MvcWeb/Startup.cs
src/Presentation/MvcWeb/Views/Shared/_LoginPartial.cshtml

Fix broken url navigation

---

src/Core/Application/Items/Queries/List/ListItemsQueryHandler.cs

Include pictures when listing items

---

src/Core/Application/Items/Commands/CreateItem/CreateItemCommandHandler.cs
src/Core/Application/SeedSampleData/Seeder.cs

Add default picture when seeding items and creating item without any pictures

---

Tests/Persistence.IntegrationTests/AuctionSystemDbContextTests.cs
src/Core/Application/Items/Commands/CreateItem/CreateItemCommand.cs
src/Core/Domain/Common/AuditableEntity.cs
src/Core/Domain/Entities/Bid.cs
src/Infrastructure/Persistence/AuctionSystemDbContext.cs
src/Infrastructure/Persistence/Configurations/BidConfiguration.cs
src/Infrastructure/Persistence/DesignTimeDbContextFactory.cs
src/Infrastructure/Persistence/Migrations/20200515095428_RemoveBidTableMadeOnColumn.Designer.cs
src/Infrastructure/Persistence/Migrations/20200515095428_RemoveBidTableMadeOnColumn.cs

Save utc datetime in db

---

src/Core/Application/Users/Commands/Jwt/Refresh/JwtRefreshTokenCommandHandler.cs
src/Presentation/Api/Extensions/ServiceCollectionExtensions.cs
src/Presentation/Api/Startup.cs

Fix authorize attribute to validate jwt token lifetime

---

src/Core/Application/Users/Commands/Jwt/Refresh/JwtRefreshTokenCommandHandler.cs

Fix authorize attribute jwt token expiration time validation

---

src/Core/Application/Admin/Queries/List/ListAllUsersQueryHandler.cs
src/Core/Application/Common/Helpers/PaginationHelper.cs
src/Core/Application/Items/Queries/List/ListItemsQueryHandler.cs

Fix pagination

---

src/Core/Application/Users/Commands/Jwt/Refresh/JwtRefreshTokenCommandHandler.cs

Delete old refresh token instead of storing it marked as used

---

src/Core/Application/Common/Helpers/PaginationHelper.cs
src/Core/Application/Common/Models/PagedResponse.cs

Add TotalDataCount property in PagedResponse

---

Tests/Application.UnitTests/Items/Queries/ListItemsQueryHandlerTests.cs

Fix unit tests

---

src/Presentation/Api/Models/ItemsFilter.cs

Fix binding in ItemsController GET action

---

src/Presentation/SpaWeb/src/components/Bid/Bid.jsx
src/Presentation/SpaWeb/src/components/Items/Details/SideBar.jsx

Check whether bid exists and set initial bidAmount

---

src/Presentation/SpaWeb/.env
src/Presentation/SpaWeb/src/services/itemsService.js

Set default picture url in case item pictures are missing

---

src/Presentation/SpaWeb/src/components/Items/Edit/Edit.jsx
src/Presentation/SpaWeb/src/utils/hooks/useCounter.js

Fix time counter in Spa not displaying correct time

---

Tests/Application.UnitTests/Bids/Queries/GetHighestBidDetailsQueryHandlerTests.cs
src/Core/Domain/Entities/Bid.cs
src/Infrastructure/Persistence/Configurations/BidConfiguration.cs
src/Infrastructure/Persistence/Configurations/ItemConfiguration.cs
src/Infrastructure/Persistence/Migrations/20200622181552_AddSetNullDeleteBehaviourForItemIdColumn.Designer.cs
src/Infrastructure/Persistence/Migrations/20200622181552_AddSetNullDeleteBehaviourForItemIdColumn.cs
src/Infrastructure/Persistence/Persistence.csproj

Make ItemId property nullable

---

Tests/Application.UnitTests/Admin/Commands/CreateAdminCommandTests.cs
Tests/Application.UnitTests/Admin/Commands/DeleteAdminCommandTests.cs
Tests/Application.UnitTests/Setup/AuctionSystemContextFactory.cs
src/Core/Application/Admin/Commands/CreateAdmin/CreateAdminCommandHandler.cs
src/Core/Application/Admin/Commands/DeleteAdmin/DeleteAdminCommandHandler.cs
src/Core/Application/Common/Interfaces/IUserManager.cs
src/Core/Application/Common/Models/ErrorType.cs
src/Core/Application/Common/Models/Result.cs
src/Core/Application/ExceptionMessages.cs
src/Core/Application/Users/Commands/LoginUser/LoginUserCommandHandler.cs
src/Infrastructure/AuctionSystem.Infrastructure/Identity/IdentityResultExtensions.cs
src/Infrastructure/AuctionSystem.Infrastructure/Identity/UserManagerService.cs
src/Presentation/SpaWeb/src/components/PrivateRoute.jsx
src/Presentation/SpaWeb/src/utils/helpers/api.js

Invalidate user token when demoted

---

src/Core/Application/SeedSampleData/Seeder.cs
src/Infrastructure/AuctionSystem.Infrastructure/Identity/UserManagerService.cs

Seed refresh token for each seeded user

---

src/Presentation/Api/appsettings.json

Make Redis cache optional

---

src/Presentation/MvcWeb/Startup.cs

Remove duplicate IEmailSender injection
